version: '3.8'

services:
  milk-quality:
    build: .
    container_name: milk_quality_container
    volumes:
      - .:/app
    command: >
      jupyter nbconvert --to notebook --execute --inplace Milk_Quality_Prediction.ipynb