version: '3.8'

services:
  milk-quality-app:
    build: .
    container_name: milk-app
    ports:
      - "5000:5000"
    restart: always
    environment:
      - FLASK_ENV=production
    command: python app.py
